"""initial_models

Revision ID: 5877655187a2
Revises: 
Create Date: 2026-06-09 12:27:18.830414
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5877655187a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_file',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('index_series',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('normative_category', sa.String(length=100), nullable=True),
    sa.Column('classification_ref', sa.String(length=100), nullable=True, comment='ATECO/ECOICOP reference'),
    sa.Column('frequency', sa.String(length=20), nullable=True, comment='monthly|quarterly|yearly'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('motivation', sa.Text(), nullable=True),
    sa.Column('algorithm_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classification_decision',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('selected_family', sa.String(length=100), nullable=True),
    sa.Column('candidate_families_json', sa.Text(), nullable=True, comment='JSON array of candidates'),
    sa.Column('selected_index_series_id', sa.String(length=50), nullable=True),
    sa.Column('classification_confidence', sa.String(length=20), nullable=True, comment='high|medium|low'),
    sa.Column('manual_override', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case_file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('contract_context',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('contract_type', sa.String(length=50), nullable=True, comment='service|supply|mixed'),
    sa.Column('is_duration_contract', sa.Boolean(), nullable=True),
    sa.Column('instant_execution', sa.Boolean(), nullable=True),
    sa.Column('stipulation_date', sa.Date(), nullable=True),
    sa.Column('execution_start_date', sa.Date(), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('contract_amount_total', sa.Float(), nullable=True),
    sa.Column('amount_subject_to_revision', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case_file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('cpv_assignment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('cpv_code', sa.String(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('weight_percent', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('index_observation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.String(length=50), nullable=False),
    sa.Column('ref_period', sa.Date(), nullable=False, comment='period start date'),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('is_definitive', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['index_series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('override_reason',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('field_path', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revision_input',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('base_period', sa.Date(), nullable=True),
    sa.Column('comparison_period', sa.Date(), nullable=True),
    sa.Column('amount_subject_to_revision', sa.Float(), nullable=True),
    sa.Column('excluded_amount', sa.Float(), nullable=True),
    sa.Column('exclusion_reason', sa.Text(), nullable=True),
    sa.Column('composite_weights_json', sa.Text(), nullable=True, comment='JSON weights for multi-index'),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case_file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('revision_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('base_value', sa.Float(), nullable=True),
    sa.Column('comparison_value', sa.Float(), nullable=True),
    sa.Column('variation_percent', sa.Float(), nullable=True),
    sa.Column('threshold_percent', sa.Float(), nullable=True),
    sa.Column('excess_percent', sa.Float(), nullable=True),
    sa.Column('recognition_percent', sa.Float(), nullable=True),
    sa.Column('revision_amount', sa.Float(), nullable=True),
    sa.Column('formula_detail', sa.Text(), nullable=True, comment='human-readable formula applied'),
    sa.Column('result_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wizard_answer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('field_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wizard_answer')
    op.drop_table('revision_result')
    op.drop_table('revision_input')
    op.drop_table('override_reason')
    op.drop_table('index_observation')
    op.drop_table('cpv_assignment')
    op.drop_table('contract_context')
    op.drop_table('classification_decision')
    op.drop_table('audit_log')
    op.drop_table('index_series')
    op.drop_table('case_file')
    # ### end Alembic commands ###
