"""widen_ateco_code

Revision ID: 5dedb114c3db
Revises: eeb76f51f478
Create Date: 2026-08-26 10:09:18.461451
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5dedb114c3db'
down_revision: Union[str, None] = 'eeb76f51f478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cpv_tabella_d_association', 'ateco_code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cpv_tabella_d_association', 'ateco_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
