"""add_saved_sdmx_queries

Revision ID: 9b3c7a1d4e20
Revises: 5dedb114c3db
Create Date: 2026-09-01 12:00:00.000000

Salvataggio automatico delle query SDMX importate: una riga per URL
normalizzata (index_import_query) e i link verso le serie toccate
(index_import_query_series). La cancellazione della query o della serie
rimuove i link in cascata; le osservazioni restano.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '9b3c7a1d4e20'
down_revision: Union[str, None] = '5dedb114c3db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Alembic requires module-level revision variables; CodeQL flags as unused - mark as intentionally used
__all__ = ["revision", "down_revision", "branch_labels", "depends_on", "upgrade", "downgrade"]

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_import_query',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('dataflow_id', sa.String(length=100), nullable=False),
    sa.Column('key_part', sa.String(length=255), nullable=False),
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.Column(
        'updated_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('index_import_query_series',
    sa.Column('query_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('series_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['index_import_query.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['index_series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('query_id', 'series_id'),
    sa.UniqueConstraint('query_id', 'series_id', name='uq_query_series')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('index_import_query_series')
    op.drop_table('index_import_query')
    # ### end Alembic commands ###