"""create ateco_catalog

Revision ID: a55298447445
Revises: d026631a699f
Create Date: 2026-06-10 09:08:53.696622
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a55298447445'
down_revision: Union[str, None] = 'd026631a699f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ateco_catalog',
    sa.Column('ateco_code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ateco_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ateco_catalog')
    # ### end Alembic commands ###
