"""support_catalogs

Revision ID: d026631a699f
Revises: 5877655187a2
Create Date: 2026-06-09 12:30:27.859410
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd026631a699f'
down_revision: Union[str, None] = '5877655187a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpv_catalog',
    sa.Column('cpv_code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cpv_code')
    )
    op.create_table('family_definition',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_mapping',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('cpv_pattern', sa.String(length=20), nullable=False),
    sa.Column('family', sa.String(length=50), nullable=False),
    sa.Column('strength', sa.String(length=20), nullable=False, comment='strong|medium|weak'),
    sa.Column('mapping_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('normative_param',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('normative_param')
    op.drop_table('family_mapping')
    op.drop_table('family_definition')
    op.drop_table('cpv_catalog')
    # ### end Alembic commands ###
