"""add_tabella_d

Revision ID: eeb76f51f478
Revises: fd5046b52fcb
Create Date: 2026-08-26 10:04:00.334265
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eeb76f51f478'
down_revision: Union[str, None] = 'fd5046b52fcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpv_tabella_d_association',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cpv_code', sa.String(length=20), nullable=False),
    sa.Column('table_class', sa.String(length=10), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('index_type', sa.String(length=4), nullable=False),
    sa.Column('classification', sa.String(length=10), nullable=False),
    sa.Column('ateco_code', sa.String(length=10), nullable=False),
    sa.Column('index_description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cpv_tabella_d_association_cpv_code'), 'cpv_tabella_d_association', ['cpv_code'], unique=False)
    op.create_table('cpv_tabella_d_master',
    sa.Column('cpv_code', sa.String(length=20), nullable=False),
    sa.Column('cpv_description', sa.Text(), nullable=False),
    sa.Column('table_class', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('cpv_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cpv_tabella_d_master')
    op.drop_index(op.f('ix_cpv_tabella_d_association_cpv_code'), table_name='cpv_tabella_d_association')
    op.drop_table('cpv_tabella_d_association')
    # ### end Alembic commands ###
