"""add updated_at to ateco_catalog

Revision ID: f7ba43f2dd2e
Revises: a55298447445
Create Date: 2026-06-10 09:39:00.148995
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f7ba43f2dd2e'
down_revision: Union[str, None] = 'a55298447445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ateco_catalog', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ateco_catalog', 'updated_at')
    # ### end Alembic commands ###
