"""add_unique_constraint_series_ref_period

Revision ID: fd5046b52fcb
Revises: 58143e45e4ff
Create Date: 2026-06-15 12:10:08.965086
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fd5046b52fcb'
down_revision: Union[str, None] = '58143e45e4ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_series_ref_period', 'index_observation', ['series_id', 'ref_period'])
    op.alter_column('tol_assignment', 'weight_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Peso percentuale della TOL (per multi-TOL deve sommare a 100)',
               existing_nullable=False,
               existing_server_default=sa.text("'100'::double precision"))
    op.alter_column('tol_assignment', 'amount_allocated',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Importo allocato a questa TOL (calcolato da peso%)',
               existing_nullable=True)
    op.drop_index('ix_tol_assignment_case_id', table_name='tol_assignment')
    op.drop_index('ix_tol_assignment_tol_code', table_name='tol_assignment')
    op.drop_constraint('tol_assignment_case_id_fkey', 'tol_assignment', type_='foreignkey')
    op.create_foreign_key(None, 'tol_assignment', 'case_file', ['case_id'], ['id'])
    op.alter_column('tol_index_series', 'series_id',
               existing_type=sa.VARCHAR(length=100),
               comment='ID della serie ISTAT/MIT associata alla TOL',
               existing_nullable=False)
    op.drop_index('ix_tol_index_series_active', table_name='tol_index_series')
    op.drop_index('ix_tol_index_series_series_id', table_name='tol_index_series')
    op.drop_index('ix_tol_index_series_tol_code', table_name='tol_index_series')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tol_index_series_tol_code', 'tol_index_series', ['tol_code'], unique=False)
    op.create_index('ix_tol_index_series_series_id', 'tol_index_series', ['series_id'], unique=False)
    op.create_index('ix_tol_index_series_active', 'tol_index_series', ['is_active'], unique=False)
    op.alter_column('tol_index_series', 'series_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='ID della serie ISTAT/MIT associata alla TOL',
               existing_nullable=False)
    op.drop_constraint(None, 'tol_assignment', type_='foreignkey')
    op.create_foreign_key('tol_assignment_case_id_fkey', 'tol_assignment', 'case_file', ['case_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_tol_assignment_tol_code', 'tol_assignment', ['tol_code'], unique=False)
    op.create_index('ix_tol_assignment_case_id', 'tol_assignment', ['case_id'], unique=False)
    op.alter_column('tol_assignment', 'amount_allocated',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Importo allocato a questa TOL (calcolato da peso%)',
               existing_nullable=True)
    op.alter_column('tol_assignment', 'weight_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Peso percentuale della TOL (per multi-TOL deve sommare a 100)',
               existing_nullable=False,
               existing_server_default=sa.text("'100'::double precision"))
    op.drop_constraint('uq_series_ref_period', 'index_observation', type_='unique')
    # ### end Alembic commands ###
