import { useState } from 'react'

interface TolEntry {
  code: string
  label: string
  description: string
  isSpecialized: boolean
}

const TOL_DATA: TolEntry[] = [
  { code: 'TOL.1',  label: 'Opere edili su edifici e manufatti non soggetti a tutela dei beni culturali', isSpecialized: false, description: 'Riguarda la nuova costruzione, la manutenzione, la ristrutturazione o il consolidamento di edifici civili e industriali non soggetti a tutela dei beni culturali quali, in via esemplificativa, le residenze, le carceri, le scuole, le caserme, gli uffici, i teatri, gli ospedali, gli stadi, gli edifici per le industrie, gli edifici per parcheggi, le stazioni ferroviarie e metropolitane e gli edifici aeroportuali. Include, in via esemplificativa e non esaustiva: infissi e rivestimenti interni ed esterni, pavimentazioni, massetti e sottofondi, solai (esclusi quelli interamente in cemento armato), altri manufatti in materie plastiche, materiali vetrosi e simili, murature e tramezzature comprensive di intonacatura, rasatura, tinteggiatura, verniciatura, opere di finitura quali isolamenti termici e acustici, controsoffittature, barriere al fuoco e opere di impermeabilizzazione, facciate continue e coperture in alluminio, apparecchi di appoggio in gomma. Sono da escludere: Impianti elettrici, tecnologici, radiotelefonici, antintrusione, meccanici, termici, di condizionamento, idrico sanitari e trasportatori, le strutture e i manufatti in legno, in acciaio (travi, coperture, ecc.), in cemento armato gettato in opera o prefabbricato (pilastri, travi, pozzetti, serbatoi pensili e silos), gli scavi e i movimenti terra, le demolizioni, la raccolta di materiali di risulta e il loro smaltimento e qualsiasi lavorazione o materiale direttamente riconducibile alle T.O.L. Specializzate.' },
  { code: 'TOL.2',  label: 'Opere edili su edifici e manufatti soggetti a tutela dei beni culturali', isSpecialized: false, description: 'Riguarda la manutenzione, la ristrutturazione o il consolidamento di edifici civili e industriali soggetti a tutela dei beni culturali quali, in via esemplificativa, le residenze, le carceri, le scuole, gli ospedali, le caserme, gli uffici, i teatri, gli stadi, gli edifici per le industrie, gli edifici per parcheggi, le stazioni ferroviarie e metropolitane e gli edifici aeroportuali. Include, in via esemplificativa e non esaustiva: infissi e rivestimenti interni ed esterni, pavimentazioni, massetti e sottofondi, solai (esclusi quelli interamente in cemento armato), altri manufatti in materie plastiche, materiali vetrosi e simili, murature e tramezzature comprensive di intonacatura, rasatura, tinteggiatura, verniciatura, opere di finitura quali isolamenti termici e acustici, controsoffittature, barriere al fuoco e opere di impermeabilizzazione, facciate continue e coperture in alluminio, apparecchi di appoggio in gomma. Sono da escludere: Impianti elettrici, tecnologici, radiotelefonici, antintrusione, meccanici, termici, di condizionamento, idrico sanitari e trasportatori, le strutture e i manufatti in legno, in acciaio (travi, coperture, ecc.), in cemento armato gettato in opera o prefabbricato (pilastri, travi, pozzetti, serbatoi pensili e silos), gli scavi e i movimenti terra, le demolizioni, la raccolta di materiali di risulta e il loro smaltimento e qualsiasi lavorazione o materiale direttamente riconducibile alle T.O.L. Specializzate.' },
  { code: 'TOL.3',  label: 'Scavi archeologici, restauri specialistici di beni del patrimonio culturale e di interesse storico', isSpecialized: true, description: 'Riguarda gli scavi archeologici e le attività strettamente connesse da eseguirsi sia in aree dichiarate di interesse culturale sia in aree non dichiarate, condotti secondo normativa vigente. Per scavi archeologici si intendono anche quelli preparatori alla nuova costruzione, alla ristrutturazione, al restauro ed alla manutenzione da progettarsi, eseguirsi ed effettuarsi da imprese in possesso dei requisiti e della manodopera specializzata, secondo normativa vigente. Sono altresì inclusi gli scavi archeologici subacquei. Riguarda interventi relativi alla conservazione, alla diagnostica, al monitoraggio, alla manutenzione e al restauro di beni culturali di qualsiasi genere e materiale in tutti i tipi di contesto - museale, archeologico, di cantiere e/o laboratorio - effettuati da imprese qualificate e mano d\'opera specializzata secondo la normativa vigente. Include la lavorazione di beni culturali mobili, superfici decorate e materiali storicizzati di beni architettonici ed archeologici, di beni demoetnoantropologici e di qualsiasi altro bene di interesse culturale appartenente a soggetti pubblici e privati, come stabilito dal Dlgs 42/2004.' },
  { code: 'TOL.4',  label: 'Lavori di movimento terra, demolizioni, opere di protezione ambientale, ingegneria naturalistica e opere a verde', isSpecialized: true, description: 'Riguarda lo scavo e i movimenti terra di qualsiasi genere, trincee e rilevati, ripristino, modifica e bonifica di volumi di terra, realizzati qualunque sia la natura del terreno da scavare, ripristinare e bonificare, i campionamenti di terreni e le analisi chimiche, le demolizioni in genere, compreso lo smontaggio di impianti, la demolizione completa di edifici e il taglio di strutture in cemento armato, le attività di raccolta dei materiali di risulta ed il loro conferimento, la realizzazione delle cunette, caditoie, canalette in terra o in calcestruzzo direttamente relazionate con i movimenti terra, la realizzazione del verde urbano, compresi gli arredi urbani e le opere a verde quali la realizzazione di tappeti erbosi, inerbimenti, la messa a dimora di piante arbustive o alberi, la piantagione di essenze arboree e la manutenzione del verde in generale, compresi i geotessuti, le geogriglie, le terre rinforzate, i materiali in grado di aumentare la capacità portante del rilevato, dune antirumore, la stabilizzazione a calce e/o cemento, il misto stabilizzato, il misto cementato e le trincee drenanti.' },
  { code: 'TOL.5',  label: 'Pavimentazioni in conglomerato bituminoso', isSpecialized: false, description: 'Riguarda la nuova costruzione, la manutenzione o la ristrutturazione di pavimentazioni in conglomerato bituminoso. Include in via esemplificativa e non esaustiva: le pavimentazioni stradali, di piazzali e marciapiedi, le impermeabilizzazioni a base di materiali bituminosi di impalcati, la segnaletica orizzontale. Sono da escludere: le pavimentazioni in calcestruzzo, strutture e i manufatti in acciaio, in cemento armato gettato in opera o prefabbricato, gli scavi e i movimenti terra, le demolizioni, la raccolta di materiali di risulta e il loro smaltimento, e qualsiasi lavorazione o materiale direttamente riconducibile alle T.O.L. Specializzate.' },
  { code: 'TOL.6',  label: 'Strutture, opere di ingegneria e manufatti in acciaio', isSpecialized: true, description: 'Riguarda la produzione in stabilimenti industriali, il montaggio in situ e più in generale la nuova costruzione, la manutenzione e la ristrutturazione di strutture, opere di ingegneria e manufatti realizzati in acciaio, compresi gli edifici in carpenteria pesante e leggera, ponti, viadotti e profilati, lavorazioni e trattamenti protettivi delle strutture in acciaio, i dispositivi strutturali quali, in via esemplificativa e non esaustiva, qualsiasi tipologia di giunti di dilatazione, di apparecchi di appoggio, di dispositivi di ancoraggio e di ritegni antisismici, compresi elementi quali rotaie, paraurti ferroviari, dispositivi di sicurezza stradale in acciaio (barriere di sicurezza e fonoassorbenti, attenuatori, terminali, chiusure varchi), segnaletica stradale verticale, tralicci e pali, recinzioni, lamiere per copertura chiusini, canalette, passerelle portacavi, canali di gronda, portali stradali e ferroviari, reti paramassi, scale, tubi in acciaio di qualsiasi tipologia e applicazione. Comprende inoltre le coperture particolari quali per esempio le tensostrutture e le coperture geodetiche. Sono esclusi gli acciai d\'armatura del calcestruzzo e i consolidamenti strutturali in galleria i quali si considerano inclusi nelle specifiche T.O.L. di riferimento.' },
  { code: 'TOL.7',  label: 'Strutture, opere di ingegneria e manufatti in calcestruzzo armato, anche prefabbricato', isSpecialized: true, description: 'Riguarda la nuova costruzione, la manutenzione o la ristrutturazione di strutture, opere di ingegneria e manufatti realizzati in cemento armato normale o precompresso, gettato in opera o prefabbricato, in elevazione o in fondazione, comprese le casseforme, l\'acciaio di armatura e le reti d\'acciaio elettrosaldate, compresi elementi particolari quali ad esempio, in via esemplificativa e non esaustiva, pavimentazioni in calcestruzzo, cunicoli, pozzetti, cordoli, tubi prefabbricati, traverse ferroviarie, barriere stradali tipo New Jersey ed altri profili redirettivi in calcestruzzo anche per gallerie stradali, blocchi di fondazione per pali, apparecchi di appoggio in gomma, pannelli di calcestruzzo prefabbricato, canalette ecc. Riguarda altresì la realizzazione di opere atte a migliorare la capacità resistente e la duttilità delle strutture in cemento armato o in muratura mediante l\'applicazione di materiali compositi fibrorinforzati (FRP) al fine di consentire un incremento dei carichi agenti e/o il miglioramento sismico. Comprende l\'esecuzione di rinforzi di travi, pilastri, setti, solai, volte, mediante placcaggi o fasciature di materiali compositi a matrice polimerica (FRP). Sono escluse le fondazioni speciali profonde e i rivestimenti in galleria, i quali si considerano inclusi nelle specifiche T.O.L. Specializzate.' },
  { code: 'TOL.8',  label: 'Strutture, opere di ingegneria e manufatti in legno', isSpecialized: true, description: 'Riguarda la nuova costruzione, la manutenzione o la ristrutturazione di strutture, opere di ingegneria e manufatti realizzati interamente o nella maggior parte in legno, compresi elementi particolari quali ad esempio, in via esemplificativa e non esaustiva, strutture portanti, tamponature, infissi, rivestimenti, pareti, coperture, la impermeabilizzazione o copertura con tegole o similari, scale, pavimenti, pannellature, ecc. Si includono anche la eventuale verniciatura e/o protezione esterna o interna del legno.' },
  { code: 'TOL.9',  label: 'Gallerie e opere d\'arte nel sottosuolo realizzate con metodo tradizionale', isSpecialized: false, description: 'Riguarda la nuova costruzione attraverso il metodo di scavo tradizionale e la manutenzione, la ristrutturazione e la messa in sicurezza delle opere d\'arte in sotterraneo, qualsiasi sia il loro grado di importanza. Comprende in via esemplificativa gallerie naturali, trafori, passaggi sotterranei, tunnel, rivestimenti primari e definitivi, impermeabilizzazioni, strati separatori, segnaletica di emergenza, perforazioni e iniezioni, infilaggi sub orizzontali, armatura metallica e conglomerato cementizio per opere di sostegno e consolidamento, le centine e le opere di finitura. Sono esclusi: gli impianti elettrici e tecnologici per la sicurezza in galleria (Es: impianti di ventilazione, ecc.), pavimentazioni in conglomerato bituminoso e profili redirettivi, riconducibili alle T.O.L. Specializzate.' },
  { code: 'TOL.10', label: 'Gallerie e opere d\'arte nel sottosuolo realizzate con metodo meccanizzato', isSpecialized: false, description: 'Riguarda la nuova costruzione attraverso il metodo di scavo meccanizzato. Comprende in via esemplificativa gallerie naturali, trafori, passaggi sotterranei, tunnel, rivestimenti, impermeabilizzazioni, strati separatori, segnaletica di emergenza, perforazioni e iniezioni, infilaggi sub orizzontali, armatura metallica e conglomerato cementizio per opere di sostegno e consolidamento, opere di finitura, ecc. Sono esclusi gli impianti elettrici e tecnologici per la sicurezza in galleria (Es: impianti di ventilazione, ecc.), pavimentazioni in conglomerato bituminoso e profili redirettivi, riconducibili alle T.O.L. Specializzate.' },
  { code: 'TOL.11', label: 'Acquedotti, gasdotti, opere di irrigazione e fognature', isSpecialized: false, description: 'Riguarda la costruzione, la manutenzione o la ristrutturazione di interventi a rete, gli acquedotti, le fognature, i gasdotti, gli oleodotti, le torri piezometriche, la rete di distribuzione all\'utente finale, che siano necessari per attuare il "servizio idrico integrato" ovvero per trasportare ai punti di utilizzazione fluidi aeriformi o liquidi. Include, in via esemplificativa e non esaustiva: la fornitura e la posa in opera delle tubazioni e dei manufatti idraulici in materiale plastico e di tutte le componenti accessorie, gli impianti elettromeccanici di sollevamento, realizzate all\'aperto e/o in galleria. Sono da escludere: gli impianti (per ambienti interni) elettromeccanici, meccanici, idrico-sanitari, elettrici, elettronici e trasportatori, le strutture e i manufatti in acciaio, in cemento armato gettato in opera o prefabbricato, comprese le tubazioni in acciaio o in cemento armato, gli scavi e i movimenti terra, le demolizioni, la raccolta di materiali di risulta, la loro separazione, il conferimento e l\'eventuale riciclaggio e qualsiasi lavorazione o materiale direttamente riconducibile alle T.O.L. Specializzate.' },
  { code: 'TOL.12', label: 'Opere marittime e lavori di dragaggio, opere fluviali e di difesa del suolo', isSpecialized: false, description: 'Riguarda la costruzione, la manutenzione o la ristrutturazione di interventi comunque realizzati, in acque dolci e salate, che costituiscono terminali per la mobilità su "acqua" ovvero opere di difesa del territorio dalle stesse acque dolci o salate, compresa la pulizia o bonifica idraulica. Include, in via esemplificativa e non esaustiva: scavi in alveo, scavi per l\'apertura di nuovi canali, formazione di rilevati arginali, realizzazione di scogliere e relativi strati di base e a protezione delle fondazioni, le perforazioni, le iniezioni di miscele di acqua e cemento e le tubazioni in resina per interventi di consolidamento, la fornitura e la posa in opera di gabbioni metallici, le lavorazioni finalizzate alla difesa e/o bonifica del mare e dei fiumi. Sono da escludere: gli impianti elettromeccanici, meccanici, idrico-sanitari, elettrici, telefonici, elettronici e di sollevamento, le strutture e i manufatti in legno, in acciaio, in cemento armato gettato in opera o prefabbricato, comprese le tubazioni in acciaio o in cemento armato, gli scavi e i movimenti terra diversi da quelli esplicitamente inclusi, le demolizioni, la raccolta di materiali di risulta, la loro separazione, il conferimento e l\'eventuale riciclaggio e qualsiasi lavorazione o materiale direttamente riconducibile alle T.O.L. Specializzate.' },
  { code: 'TOL.13', label: 'Impianti per la produzione, trasformazione e distribuzione di energia elettrica in alta e media tensione, per la trazione elettrica e l\'illuminazione pubblica', isSpecialized: false, description: 'Riguarda la costruzione, la manutenzione o la ristrutturazione degli interventi a rete che sono necessari per la produzione, distribuzione ad alta e media tensione e per la trasformazione e distribuzione a bassa tensione all\'utente finale di energia elettrica, gli impianti fotovoltaici, gli impianti eolici, geotermici e gli impianti di cogenerazione; la costruzione, la manutenzione e la ristrutturazione degli impianti di pubblica illuminazione, da realizzare all\'esterno degli edifici; la costruzione, la manutenzione o ristrutturazione degli impianti per la trazione elettrica di qualsiasi ferrovia, metropolitana o linea tranviaria. Include, in via esemplificativa e non esaustiva: le turbine, i generatori, i pannelli fotovoltaici, le centrali e le cabine di trasformazione, i conduttori e cavi elettrici per qualsiasi numero di fasi su tralicci, pali o interrati, le canalizzazioni, i sistemi di controllo e automazione, i quadri, gli switch, i trasformatori, gli isolatori, gli scaricatori di tensione, le unità di alimentazione, sezionamento e misura/diagnostica, gli interruttori, i raddrizzatori, le sospensioni, gli apparecchi di appoggio in gomma, i morsetti, gli impianti di messa a terra, gli apparecchi di illuminazione stradale, ecc. Sono da escludere: le strutture e i manufatti in acciaio (Es: tralicci, pali, ecc.), in cemento armato prefabbricato o gettato in opera (Es: fondazioni, muri, pozzetti, ecc.), gli scavi e i movimenti terra, le fondazioni profonde, le demolizioni e qualsiasi lavorazione o materiale direttamente riconducibile alle relative T.O.L. Specializzate.' },
  { code: 'TOL.14', label: 'Impianti elettrici, tecnologici, radiotelefonici e antintrusione', isSpecialized: true, description: 'Riguarda la fornitura, l\'installazione, la manutenzione o la ristrutturazione di un insieme di impianti elettrici, tecnologici, antintrusione, antincendio (esclusa la parte idraulica), telefonici, radiotelefonici, televisivi nonché di reti di trasmissione dati e simili, per fabbricati e per la sicurezza in galleria. Include, in via esemplificativa e non esaustiva: le cabine, gli armadi, i quadri elettrici, i cavi, le centraline di controllo a distanza, i rilevatori gas, le videocamere, gli apparecchi illuminanti da interno, i gruppi di continuità, ecc. Sono da escludere: gli impianti meccanici, termici, di condizionamento, idrico sanitari e trasportatori, le strutture e i manufatti in acciaio, in cemento armato gettato in opera o prefabbricato e in legno, gli scavi e i movimenti terra, le demolizioni e qualsiasi lavorazione o materiale direttamente riconducibile alle altre T.O.L. Specializzate.' },
  { code: 'TOL.15', label: 'Impianti meccanici, termici, di condizionamento, idrico sanitari e trasportatori', isSpecialized: true, description: 'Riguarda la fornitura, l\'installazione, la manutenzione o la ristrutturazione di impianti meccanici, idrosanitari, del gas, antincendio (solo la parte idraulica), termici e per il condizionamento del clima, pneumatici e di sollevamento e trasporto, per fabbricati e per la sicurezza in galleria. Include, in via esemplificativa e non esaustiva: le tubazioni in materiale plastico di adduzione e di scarico, i raccordi, le valvole, le pompe, le caldaie, i condizionatori, i sistemi di ventilazione dell\'aria, i filtri, i sanitari, le cassette di scarico, gli idranti, gli ascensori, le scale mobili, ecc. Sono da escludere: le strutture e i manufatti in acciaio, in cemento armato gettato in opera o prefabbricato, in legno, gli scavi e i movimenti terra, le demolizioni, la raccolta di materiali di risulta e il loro conferimento, non direttamente relazionati con gli stessi impianti e qualsiasi lavorazione o materiale direttamente riconducibile alle altre T.O.L. Specializzate.' },
  { code: 'TOL.16', label: 'Impianti di potabilizzazione e depurazione', isSpecialized: false, description: 'Riguarda la fornitura, l\'installazione, la manutenzione o la ristrutturazione di impianti di potabilizzazione e depurazione. Include, in via esemplificativa e non esaustiva: le tubazioni in materiale plastico di adduzione e di scarico, i raccordi, le valvole, le pompe, i filtri, la ghiaia e sabbia, le centrifughe, le coclee, i ventilatori, ecc. Sono da escludere: le strutture e i manufatti in acciaio, in cemento armato gettato in opera o prefabbricato, in legno, i movimenti terra, le demolizioni, non direttamente relazionati con gli stessi impianti e qualsiasi lavorazione o materiale direttamente riconducibile alle altre T.O.L. Specializzate.' },
  { code: 'TOL.17', label: 'Impianti di segnalamento, sicurezza del traffico e telecomunicazioni', isSpecialized: false, description: 'Riguarda la nuova costruzione, la manutenzione o la ristrutturazione di impianti di telecomunicazioni e gli impianti automatici per la segnaletica luminosa e la sicurezza del traffico stradale, ferroviario, metropolitano o tranviario, aeroportuale, compreso il rilevamento e l\'elaborazione delle informazioni. Include, in via esemplificativa e non esaustiva: le tecnologie hardware e software di elaborazione dei dati per il controllo a distanza, i sistemi di radiotrasmissione dei dati, i quadri, gli apparecchi di segnalazione luminosa, i pannelli a messaggio variabile, i sistemi di automazione e manovra elettrica, i sistemi di alimentazione, i sistemi di monitoraggio e diagnostica, i cavi elettrici e di trasmissione dati, le canalizzazioni. Sono da escludere: le strutture e i manufatti in acciaio (Es: tralicci, pali, ecc.), in cemento armato gettato in opera o prefabbricato (Es: fondazioni, muri, pozzetti, ecc.), gli scavi e i movimenti terra, le demolizioni, la raccolta di materiali di risulta e il loro conferimento, e qualsiasi lavorazione o materiale direttamente riconducibile alle T.O.L. Specializzate.' },
  { code: 'TOL.18', label: 'Armamento ferroviario', isSpecialized: false, description: 'Riguarda la nuova costruzione, la manutenzione o la ristrutturazione dei binari per qualsiasi ferrovia, metropolitana o linea tranviaria. Include, in via esemplificativa e non esaustiva: la nuova costruzione, il rinnovo, il risanamento e la demolizione di binari; la posa e la rimozione del ballast, di traverse, rotaie, giunti, scambi, paraurti, ecc.; il taglio, la molatura e la saldatura di rotaie e scambi, il livellamento del ballast, ecc. Sono da escludere: la fornitura e lo smaltimento di ballast, di strutture e i manufatti in acciaio (Es: rotaie, scambi, paraurti, ecc.), e in cemento armato gettato in opera o prefabbricato (Es: traverse in c.a.p., muretti paraballast, ecc.), gli scavi e i movimenti terra, le demolizioni di opere civili, la raccolta di terreni di risulta e residui di demolizioni ed il loro smaltimento e qualsiasi lavorazione o materiale direttamente riconducibile alle T.O.L. Specializzate.' },
  { code: 'TOL.19', label: 'Opere di fondazione speciale, indagini geologiche e geotecniche', isSpecialized: true, description: 'Riguarda la costruzione di opere destinate a trasferire i carichi di manufatti poggianti su terreni non idonei a reggere i carichi stessi, di opere destinate a conferire ai terreni caratteristiche di resistenza e di indeformabilità tali da rendere stabili l\'imposta dei manufatti e da prevenire dissesti geologici, di opere per rendere antisismiche le strutture esistenti e funzionanti e l\'esecuzione di indagini geognostiche ed esplorazioni del sottosuolo con mezzi speciali, anche ai fini ambientali, compreso il prelievo di campioni di terreno o di roccia e l\'esecuzione di prove in situ. Comprende in via esemplificativa e non esaustiva: l\'esecuzione di pali, micropali, palancolate e diaframmi di qualsiasi tipo, di sottofondazioni, di palificate e muri di sostegno speciali, di ancoraggi, di opere per ripristinare la funzionalità statica delle strutture, di pozzi, di opere per garantire la stabilità dei pendii e di lavorazioni speciali per il prosciugamento, l\'impermeabilizzazione ed il consolidamento di terreni e dei piani di posa dei rilevati. Sono compresi inoltre, i monitoraggi geotecnici e strutturali e tutte le relative attrezzature, sondaggi geognostici, scavi esplorativi e prelievi di aggregati.' },
  { code: 'TOL.20', label: 'Conferimento rifiuti a impianto di smaltimento o recupero', isSpecialized: true, description: 'Riguarda lo smaltimento o recupero a discarica di qualsiasi tipo di rifiuto pericoloso o non pericoloso, prodotto ed autorizzato in ogni singolo progetto, costituito, in via esemplificativa e non esaustiva, da terre da scavi o perforazioni a cielo aperto, da scavi o perforazioni nel sottosuolo, da pietrisco di massicciate ferroviarie e dalle operazioni di demolizione, per i quali è particolarmente difficile determinare la specifica tipologia e quantità.' },
]

export default function TolCatalog() {
  const [expanded, setExpanded] = useState<string | null>(null)

  return (
    <div>
      <div style={{
        background: 'var(--color-bg-card)', padding: 24, borderRadius: 12, marginBottom: 16,
        boxShadow: '0 1px 3px var(--color-shadow)',
      }}>
        <h2 style={{ margin: '0 0 4px', fontSize: 20 }}>Tipologie Omogenee Lavorazioni (TOL)</h2>
        <p style={{ margin: 0, color: 'var(--color-text-muted)', fontSize: 14 }}>
          Tabella A.1 — Elenco delle venti TOL e relative declaratorie (Tabella A.2) — Allegato II.2-bis D.Lgs. 36/2023
        </p>
      </div>

      <div style={{
        background: 'var(--color-bg-card)', borderRadius: 12, overflow: 'hidden',
        boxShadow: '0 1px 3px var(--color-shadow)',
      }}>
        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
          <thead>
            <tr style={{ borderBottom: '2px solid #e5e7eb', background: 'var(--color-bg-offset)' }}>
              <th style={{ textAlign: 'left', padding: '10px 14px', color: 'var(--color-text-muted)', fontWeight: 600, width: 90 }}>Codice</th>
              <th style={{ textAlign: 'left', padding: '10px 14px', color: 'var(--color-text-muted)', fontWeight: 600 }}>Descrizione</th>
              <th style={{ textAlign: 'center', padding: '10px 14px', color: 'var(--color-text-muted)', fontWeight: 600, width: 100 }}>Tipo</th>
              <th style={{ textAlign: 'center', padding: '10px 14px', color: 'var(--color-text-muted)', fontWeight: 600, width: 60 }}></th>
            </tr>
          </thead>
          <tbody>
            {TOL_DATA.map(tol => {
              const isOpen = expanded === tol.code
              return (
                <>
                  <tr
                    key={tol.code}
                    onClick={() => setExpanded(isOpen ? null : tol.code)}
                    style={{
                      borderBottom: '1px solid #f3f4f6', cursor: 'pointer',
                      background: isOpen ? 'var(--color-bg-offset)' : undefined,
                    }}
                  >
                    <td style={{ padding: '12px 14px', fontWeight: 700, fontFamily: 'monospace', color: 'var(--color-primary)' }}>
                      {tol.code}
                    </td>
                    <td style={{ padding: '12px 14px', color: 'var(--color-text-secondary)' }}>{tol.label}</td>
                    <td style={{ padding: '12px 14px', textAlign: 'center' }}>
                      <span style={{
                        padding: '2px 8px', borderRadius: 10, fontSize: 11, fontWeight: 600,
                        background: tol.isSpecialized ? 'var(--color-bg-info)' : 'var(--color-border-lighter)',
                        color: tol.isSpecialized ? 'var(--color-text-info)' : 'var(--color-text-muted)',
                      }}>
                        {tol.isSpecialized ? 'Specializzata' : 'Generale'}
                      </span>
                    </td>
                    <td style={{ padding: '12px 14px', textAlign: 'center', color: 'var(--color-text-light)' }}>
                      {isOpen ? '▲' : '▼'}
                    </td>
                  </tr>
                  {isOpen && (
                    <tr key={`${tol.code}-desc`}>
                      <td colSpan={4} style={{ padding: '0 14px 14px 14px' }}>
                        <div style={{
                          padding: 12, background: 'var(--color-bg-offset)', borderRadius: 8,
                          fontSize: 12, color: 'var(--color-text-secondary)', lineHeight: 1.7,
                          borderLeft: '3px solid #1a1a2e',
                        }}>
                          {tol.description}
                        </div>
                      </td>
                    </tr>
                  )}
                </>
              )
            })}
          </tbody>
        </table>
      </div>
    </div>
  )
}
